-- Run with a role permitted to create the POC database, warehouse, and roles.
-- Placeholders are validated as unquoted identifiers by snowflake/setup.py.

CREATE DATABASE IF NOT EXISTS {{DATABASE}}
  COMMENT = 'Synthetic Microsoft Fabric Snowflake medallion proof of concept';
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{SCHEMA}}
  COMMENT = 'Synthetic banking source tables for Fabric Mirroring';

CREATE WAREHOUSE IF NOT EXISTS {{WAREHOUSE}}
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Cost-optimized warehouse for the Fabric Snowflake POC';

CREATE ROLE IF NOT EXISTS {{LOADER_ROLE}}
  COMMENT = 'Loads synthetic POC data only';
CREATE ROLE IF NOT EXISTS {{MIRROR_ROLE}}
  COMMENT = 'Least-privilege role used by Microsoft Fabric Mirroring';

GRANT USAGE ON WAREHOUSE {{WAREHOUSE}} TO ROLE {{LOADER_ROLE}};
GRANT USAGE ON DATABASE {{DATABASE}} TO ROLE {{LOADER_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{LOADER_ROLE}};
GRANT CREATE TABLE ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{LOADER_ROLE}};

CREATE TABLE IF NOT EXISTS {{DATABASE}}.{{SCHEMA}}.TRANSACTIONS (
  TRANSACTION_ID VARCHAR NOT NULL, ACCOUNT_ID VARCHAR NOT NULL, CUSTOMER_ID VARCHAR NOT NULL,
  MERCHANT_ID VARCHAR NOT NULL, DEVICE_ID VARCHAR, TRANSACTION_TIMESTAMP TIMESTAMP_TZ NOT NULL,
  AMOUNT NUMBER(18,2) NOT NULL, CURRENCY VARCHAR(3), TRANSACTION_TYPE VARCHAR,
  MERCHANT_CATEGORY VARCHAR, CHANNEL VARCHAR, COUNTRY VARCHAR(2), CARD_PRESENT BOOLEAN,
  TRANSACTION_STATUS VARCHAR, SOURCE_BATCH VARCHAR, PRIMARY KEY (TRANSACTION_ID)
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.{{SCHEMA}}.TRANSACTION_RISK (
  TRANSACTION_ID VARCHAR NOT NULL, RISK_SCORE FLOAT, RISK_BAND VARCHAR, MODEL_VERSION VARCHAR,
  SCORED_TIMESTAMP TIMESTAMP_TZ, RISK_FACTORS_JSON VARCHAR, SOURCE_BATCH VARCHAR,
  PRIMARY KEY (TRANSACTION_ID)
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.{{SCHEMA}}.MERCHANTS (
  MERCHANT_ID VARCHAR NOT NULL, MERCHANT_NAME VARCHAR, MERCHANT_CATEGORY VARCHAR, CITY VARCHAR,
  STATE VARCHAR, COUNTRY VARCHAR(2), MERCHANT_RISK_CATEGORY VARCHAR, SOURCE_BATCH VARCHAR,
  PRIMARY KEY (MERCHANT_ID)
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.{{SCHEMA}}.DIGITAL_SESSIONS (
  SESSION_ID VARCHAR NOT NULL, CUSTOMER_ID VARCHAR NOT NULL, DEVICE_ID VARCHAR, DEVICE_TYPE VARCHAR,
  OPERATING_SYSTEM VARCHAR, LOGIN_TIMESTAMP TIMESTAMP_TZ, LOGOUT_TIMESTAMP TIMESTAMP_TZ,
  AUTHENTICATION_METHOD VARCHAR, MFA_USED BOOLEAN, FAILED_ATTEMPTS INTEGER, COUNTRY VARCHAR(2),
  STATE VARCHAR, CITY VARCHAR, SESSION_RISK_SCORE FLOAT, ACTIVITIES_JSON VARCHAR,
  SOURCE_BATCH VARCHAR, PRIMARY KEY (SESSION_ID)
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.{{SCHEMA}}.DEVICES (
  DEVICE_ID VARCHAR NOT NULL, CUSTOMER_ID VARCHAR NOT NULL, FIRST_SEEN TIMESTAMP_TZ,
  LAST_SEEN TIMESTAMP_TZ, TRUSTED BOOLEAN, DEVICE_FINGERPRINT VARCHAR, OPERATING_SYSTEM VARCHAR,
  OPERATING_SYSTEM_VERSION VARCHAR, APP_VERSION VARCHAR, RISK_SIGNALS_JSON VARCHAR,
  SOURCE_BATCH VARCHAR, PRIMARY KEY (DEVICE_ID)
);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.{{SCHEMA}}.FRAUD_ALERTS (
  ALERT_ID VARCHAR NOT NULL, CUSTOMER_ID VARCHAR NOT NULL, TRANSACTION_ID VARCHAR,
  CREATED_TIMESTAMP TIMESTAMP_TZ, ALERT_TYPE VARCHAR, SEVERITY VARCHAR, STATUS VARCHAR,
  SIGNALS_JSON VARCHAR, INVESTIGATOR_NOTES_JSON VARCHAR, SOURCE_BATCH VARCHAR,
  PRIMARY KEY (ALERT_ID)
);

-- Fabric creates Snowflake streams for continuous replication. Enable change
-- tracking during privileged setup so the runtime mirror role does not need
-- MODIFY on source tables.
ALTER TABLE {{DATABASE}}.{{SCHEMA}}.TRANSACTIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE {{DATABASE}}.{{SCHEMA}}.TRANSACTION_RISK SET CHANGE_TRACKING = TRUE;
ALTER TABLE {{DATABASE}}.{{SCHEMA}}.MERCHANTS SET CHANGE_TRACKING = TRUE;
ALTER TABLE {{DATABASE}}.{{SCHEMA}}.DIGITAL_SESSIONS SET CHANGE_TRACKING = TRUE;
ALTER TABLE {{DATABASE}}.{{SCHEMA}}.DEVICES SET CHANGE_TRACKING = TRUE;
ALTER TABLE {{DATABASE}}.{{SCHEMA}}.FRAUD_ALERTS SET CHANGE_TRACKING = TRUE;

GRANT INSERT, UPDATE, DELETE, TRUNCATE, SELECT ON ALL TABLES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{LOADER_ROLE}};
GRANT INSERT, UPDATE, DELETE, TRUNCATE, SELECT ON FUTURE TABLES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{LOADER_ROLE}};

GRANT USAGE ON WAREHOUSE {{WAREHOUSE}} TO ROLE {{MIRROR_ROLE}};
GRANT USAGE ON DATABASE {{DATABASE}} TO ROLE {{MIRROR_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{MIRROR_ROLE}};
GRANT CREATE STREAM ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{MIRROR_ROLE}};
GRANT SELECT ON ALL TABLES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{MIRROR_ROLE}};
GRANT SELECT ON FUTURE TABLES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{MIRROR_ROLE}};
